task_and_robot_environment_name: 'solo-v1'
seed: 0
hid: [32,64]
l: 2
steps_per_epoch: 4000
n_epochs: 100000
replay_size: 1000000
gamma: 0.99
polyak: 0.995
lr: 0.001
alpha: 0.2
batch_size: 100
start_steps: 10000
update_after: 1000
update_every: 50
num_test_episodes: 10
max_ep_len: 1000
save_freq: 1
